name: Label issues new
on:
  issues:
    types:
      - moved_columns_in_project
jobs:
  show-event:
    runs-on: ubuntu-latest
    steps:
      - name: show payload
        env: 
          PAYLOAD: ${{ toJson(github.event) }}
        run: echo $PAYLOAD
  label_opened_no_milestoned_issues:
    if: ${{ github.event.action == 'opened' && github.event.issue.milestone == '' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: "FP: Unplanned"
          remove-labels: "FP: Completed, FP: Planned, FP: In Development"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
# Label opened issues with milestone as 'Planned'
  label_opened_milestoned_issues:
    if: ${{ github.event.action == 'opened' && github.event.issue.milestone != '' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues Planned
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: "FP: Planned"
          remove-labels: "FP: Completed, FP: Unplanned"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
# Label issues with milestone as 'Planned' 
  label_milestoned_issues:
    if: ${{ github.event.action == 'milestoned' && github.event.issue.state == 'open' && !contains(join(github.event.issue.labels.*.name, ''), 'Development') }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues Planned
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: "FP: Planned"
          remove-labels: "FP: Unplanned, FP: Completed"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
# Label closed issues with 'Completed' label
  label_closed_issues:
    if: ${{ github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues Completed
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: "FP: Completed"
          remove-labels: "FP: Unplanned, FP: Planned, FP: In Development"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
# Label reopened issues with milestone as 'In Development'
  label_reopened_milestoned_issues:
    if: ${{ github.event.action == 'reopened' && github.event.issue.milestone != '' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues In Development
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: "FP: In Development"
          remove-labels: "FP: Completed, FP: Unplanned, FP: Planned"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
# Remove otber FP labels when issue labeled as 'In Development'
  issue_labeled_indevelopment:
    if: ${{ github.event.action == 'labeled' && contains(join(github.event.issue.labels.*.name, ''), 'Development') }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Remove other FP labels when InDevelopment
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: "FP: In Development"
          remove-labels: "FP: Unplanned, FP: Planned"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
# Issue opened with label Bug - add Unplanned
  bug_opened:
    if: ${{ github.event.action == 'opened' && contains(join(github.event.issue.labels.*.name, ''), 'Bug') }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Set Unplanned label to confirmed bugs
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: "FP: Unplanned"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
