name: Set FP labels

on:
  issues:
    types: [labeled]

jobs:
  add-confirmed-label:
    runs-on: ubuntu-latest
    steps:
      - name: add 'Approved'
        env: 
          PAYLOAD: ${{ toJson(github.event) }}
          LABEL_NAME: ${{ github.event.label.name }}
        if: ${{ github.event.label.name  == 'Bug' }} 
        run: |
          github.GitHub.issues.addLabels({
            owner: github.context.repo.owner,
            repo: github.context.repo.repo,
            issue_number: github.event.issue.number,
            labels: ["FP: Approved"]
          });
