name: Label issues
on:
  issues:
    types:
      - opened
      - reopened
      - edited
      - closed
      - milestoned
      - demilestoned
jobs:
  label_opened_issues:
    if: ${{ github.event.action == 'opened' && github.event.issue.state == 'open' && !contains(join(github.event.issue.labels.*.name, ''), 'Development') }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: "FP: Unlanned"
          remove-labels: "FP: Unplanned, FP: Completed"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  label_closed_issues:
    if: ${{ github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: "FP: Completed"
          remove-labels: "FP: Unplanned, FP: Planned, FP: In Development"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
