name: Set FP labels

on:
  issues:
    types: [labeled]

jobs:
  add-confirmed-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        env: 
          PAYLOAD: ${{ toJson(github.event) }}
          LABEL_NAME: ${{ github.event.label.name }}
        if: ${{ github.event.label.name  == 'Bug' }} 
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          labels: "FP: Approved"
