name: Set FP labels

on:
  issues:
    types: [labeled]

jobs:
  add-confirmed-label:
    runs-on: ubuntu-latest
    steps:
      - name: add 'Approved'
        env: 
          PAYLOAD: ${{ github.context.payload }}
          LABEL_NAME: ${{ github.context.payload.label.name }}
        if: ${{ env.LABEL_NAME == 'Bug' }}
        run: echo "woot"
