name: Set FP labels

on:
  issues:
    types: [labeled]
  project_card:
    types: [moved]

jobs:
  add-approved-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ github.event.action == 'labeled' && github.event.label.name == 'Bug' }} 
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          labels: "FP: Approved"
          
  add-indevelopment-label:
    runs-on: ubuntu-latest
    steps:
      - name: add in developlent label
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        env: 
          PAYLOAD: ${{ toJson(github.event) }}
  

        
      
