name: Remove labels
on:
  project_card:
    types:
      - moved
jobs:
  remove_labels:
    if: github.event.project_card.column_id == '17506111'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: remove labels
        uses: andymckay/labeler@master
        with:
          remove-labels: "FP: Approved"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
